@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjEiLCJuYmYiOjE3MTk4MDE3ODAsImV4cCI6MTcxOTgyMzM4MCwiaWF0IjoxNzE5ODAxNzgwLCJpc3MiOiJxdWFubHlnaWFvYmFuLmNvbSIsImF1ZCI6InF1YW5seWdpYW9iYW4uY29tIn0.5JHdAPgngFsTZgXgzKRpsS6ykcYupnew1ZmOSMIKou8
###
POST  http://localhost:5073/api/meetings
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Họp giao ban",
    "startTime": "2024-06-28T15:07:58.784",
    "endTime": "2024-06-28T16:07:58.784"
}

###
GET http://localhost:5073/api/meetings?pageIndex=1&numberInPage=10
Authorization: Bearer {{token}}
###
PUT http://localhost:5073/api/meetings/active/2
Authorization: Bearer {{token}}
###
GET http://localhost:5073/api/user/4/meetings?pageIndex=1&numberInPage=10&status=Ch%C6%B0a+%C4%91%C4%83ng+k%C3%BD
Authorization: Bearer {{token}}
###
GET http://localhost:5073/api/meetings/14/attendees?pageIndex=1&numberInPage=10
###
GET http://localhost:5073/api/departments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImFkbWluIiwibmJmIjoxNzE5MjA5MTI5LCJleHAiOjE3MTkyMzA3MjksImlhdCI6MTcxOTIwOTEyOSwiaXNzIjoicXVhbmx5Z2lhb2Jhbi5jb20iLCJhdWQiOiJxdWFubHlnaWFvYmFuLmNvbSJ9.07XhrdZ2gV12klKaDEc3ARSohexl3yj3gYSzmn_-icQ
###
GET http://localhost:5073/api/rooms
Authorization: Bearer {{token}}
###
PUT  http://localhost:5073/api/user/attend
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId": 2,
    "meetingId": 1,
    "status": "Không tham gia",
    "reasonId": 2,
    "registerTime":"2024-06-28T11:15:42.227Z"
}

###
PUT  http://localhost:5073/api/user/1/info
Authorization: {{token}}
Content-Type: application/json

{
    "fullname": "Admin",
    "departmentId": 1,
    "position": "admin"
}

###
POST  http://localhost:5073/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

###
POST  http://localhost:5073/api/logout/1

###
GET   http://localhost:5073/api/user/list
Authorization: Bearer {{token}}

###
POST  http://localhost:5073/api/user/new
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "LAMHK",
    "password": "123",
    "fullname": "Hoàng Khắc Lâm",
    "departmentId": 2,
    "position": "Nhân viên"
}

###
GET  http://localhost:5073/api/user/list
Authorization: Bearer {{token}}

###
PUT http://localhost:5073/api/user/active/4
Authorization: Bearer {{token}}

###
GET  http://localhost:5073/api/reasons
Authorization: Bearer {{token}}