// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLGB.API.Data;

#nullable disable

namespace QLGB.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240706013442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLGB.API.Models.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnotherReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MeetingTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisterTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("QLGB.API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ban lãnh đạo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Khoa phẫu thuật, gây mê - Hồi sức, cấp cứu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khoa y học cổ truyền - Phục hồi chức năng"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Khoa ngoại"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Khoa mắt"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Khoa Bệnh nhiệt đới"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Khoa chẩn đoán hình ảnh"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Khoa nhi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Khoa HSTC - Chống độc - Thận nhân tạo"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Khoa Nội tổng hợp"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Khoa Nội Tim Mạch"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Khoa khám bệnh"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Khoa Răng Hàm Mặt"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Khoa Tai Mũi Họng"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Khoa Phụ Sản"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Phòng Công tác xã hội"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Phòng Điều dưỡng"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Phòng Kế hoạch tổng hợp"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Phòng Quản lý chất lượng - Đào tạo và Chỉ đạo tuyến"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Phòng Tài chính kế toán"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Phòng Tổ chức hành chính"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Phòng Vật tư kỹ thuật - Trang thiết bị và Công nghệ thông tin"
                        });
                });

            modelBuilder.Entity("QLGB.API.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("QLGB.API.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("QLGB.API.Models.Reason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReasonId");

                    b.ToTable("Reasons");

                    b.HasData(
                        new
                        {
                            ReasonId = 1,
                            IsActive = true,
                            Title = "Khác"
                        },
                        new
                        {
                            ReasonId = 2,
                            IsActive = true,
                            Title = "Nghỉ bù trực"
                        },
                        new
                        {
                            ReasonId = 3,
                            IsActive = true,
                            Title = "Khám bệnh tại phòng khám"
                        },
                        new
                        {
                            ReasonId = 4,
                            IsActive = true,
                            Title = "Ở lại khoa làm việc"
                        });
                });

            modelBuilder.Entity("QLGB.API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Hội trường 1 CS1"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Hội trường 2 CS1"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Hội trường 3 CS1"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Hội trường CS2"
                        });
                });

            modelBuilder.Entity("QLGB.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Fullname = "Admin",
                            IsActive = true,
                            Password = "MTIz",
                            Position = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("QLGB.API.Models.Attendee", b =>
                {
                    b.HasOne("QLGB.API.Models.Meeting", "Meeting")
                        .WithMany("Attendees")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLGB.API.Models.Reason", "Reason")
                        .WithMany("Attendees")
                        .HasForeignKey("ReasonId");

                    b.HasOne("QLGB.API.Models.Room", "Room")
                        .WithMany("Attendees")
                        .HasForeignKey("RoomId");

                    b.HasOne("QLGB.API.Models.User", "User")
                        .WithMany("Attendees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Reason");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLGB.API.Models.Log", b =>
                {
                    b.HasOne("QLGB.API.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLGB.API.Models.User", b =>
                {
                    b.HasOne("QLGB.API.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("QLGB.API.Models.Meeting", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("QLGB.API.Models.Reason", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("QLGB.API.Models.Room", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("QLGB.API.Models.User", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
